CREATE DATABASE IF NOT EXISTS system_monitoring_db;
USE system_monitoring_db;

CREATE TABLE IF NOT EXISTS `micei_system_monitoring` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    identification_number VARCHAR(100),
    date_recorded DATE NOT NULL,
    transaction_date DATE NOT NULL,
    branch VARCHAR(100),
    dealer VARCHAR(100),
    department VARCHAR(100),
    module VARCHAR(100),
    user_name VARCHAR(150),
    invoice_reference VARCHAR(150),
    payment_reference VARCHAR(150),
    client_name VARCHAR(200),
    amount DECIMAL(15,2) NULL,
    reason TEXT,
    approved_by VARCHAR(150),
    processed_type VARCHAR(100),
    processed_by VARCHAR(150),
    remarks TEXT,
    incident_report_image_path VARCHAR(255),
    classification VARCHAR(100),
    system_admin VARCHAR(150),
    ticket VARCHAR(150),
    status VARCHAR(100),
    offense VARCHAR(150),
    disciplinary_action VARCHAR(100),
    action_taken VARCHAR(100),
    memo_printed_at DATETIME NULL,
    memo_issued_at DATETIME NULL,
    refresher_completed_at DATETIME NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `ntr_system_monitoring` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    identification_number VARCHAR(100),
    date_recorded DATE NOT NULL,
    transaction_date DATE NOT NULL,
    branch VARCHAR(100),
    dealer VARCHAR(100),
    department VARCHAR(100),
    module VARCHAR(100),
    user_name VARCHAR(150),
    invoice_reference VARCHAR(150),
    payment_reference VARCHAR(150),
    client_name VARCHAR(200),
    amount DECIMAL(15,2) NULL,
    reason TEXT,
    approved_by VARCHAR(150),
    processed_type VARCHAR(100),
    processed_by VARCHAR(150),
    remarks TEXT,
    incident_report_image_path VARCHAR(255),
    classification VARCHAR(100),
    system_admin VARCHAR(150),
    ticket VARCHAR(150),
    status VARCHAR(100),
    offense VARCHAR(150),
    disciplinary_action VARCHAR(100),
    action_taken VARCHAR(100),
    memo_printed_at DATETIME NULL,
    memo_issued_at DATETIME NULL,
    refresher_completed_at DATETIME NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `micei_ticket_monitoring` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    branch VARCHAR(100),
    dealer VARCHAR(100),
    module VARCHAR(100),
    ticket_number VARCHAR(150) NOT NULL,
    ticket_description TEXT,
    date_created DATE NOT NULL,
    created_by VARCHAR(150),
    ticket_status VARCHAR(100) NOT NULL,
    resolved_at DATETIME NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `ntr_ticket_monitoring` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    branch VARCHAR(100),
    dealer VARCHAR(100),
    module VARCHAR(100),
    ticket_number VARCHAR(150) NOT NULL,
    ticket_description TEXT,
    date_created DATE NOT NULL,
    created_by VARCHAR(150),
    ticket_status VARCHAR(100) NOT NULL,
    resolved_at DATETIME NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `micei_access_requests` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    reference_no VARCHAR(40) NOT NULL,
    requester_name VARCHAR(150) NOT NULL,
    dealer VARCHAR(100) NOT NULL,
    department VARCHAR(100) NOT NULL,
    dmis_username VARCHAR(100) NOT NULL,
    module VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    requested_by VARCHAR(150) NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'Pending',
    it_status VARCHAR(40) NOT NULL DEFAULT 'Pending',
    grant_access TEXT NULL,
    it_notes TEXT NULL,
    it_reviewed_by VARCHAR(150) NULL,
    it_reviewed_at DATETIME NULL,
    final_decision VARCHAR(40) NULL,
    final_notes TEXT NULL,
    final_reviewed_by VARCHAR(150) NULL,
    final_reviewed_at DATETIME NULL,
    implementation_notes TEXT NULL,
    implemented_by VARCHAR(150) NULL,
    implemented_at DATETIME NULL,
    review_notes TEXT NULL,
    reviewed_by VARCHAR(150) NULL,
    reviewed_at DATETIME NULL,
    submitted_ip VARCHAR(45) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_access_request_reference (reference_no),
    INDEX idx_access_request_status (status),
    INDEX idx_access_request_username (dmis_username),
    INDEX idx_access_request_created (created_at)
);

CREATE TABLE IF NOT EXISTS `ntr_access_requests` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    reference_no VARCHAR(40) NOT NULL,
    requester_name VARCHAR(150) NOT NULL,
    dealer VARCHAR(100) NOT NULL,
    department VARCHAR(100) NOT NULL,
    dmis_username VARCHAR(100) NOT NULL,
    module VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    requested_by VARCHAR(150) NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'Pending',
    it_status VARCHAR(40) NOT NULL DEFAULT 'Pending',
    grant_access TEXT NULL,
    it_notes TEXT NULL,
    it_reviewed_by VARCHAR(150) NULL,
    it_reviewed_at DATETIME NULL,
    final_decision VARCHAR(40) NULL,
    final_notes TEXT NULL,
    final_reviewed_by VARCHAR(150) NULL,
    final_reviewed_at DATETIME NULL,
    implementation_notes TEXT NULL,
    implemented_by VARCHAR(150) NULL,
    implemented_at DATETIME NULL,
    review_notes TEXT NULL,
    reviewed_by VARCHAR(150) NULL,
    reviewed_at DATETIME NULL,
    submitted_ip VARCHAR(45) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_access_request_reference (reference_no),
    INDEX idx_access_request_status (status),
    INDEX idx_access_request_username (dmis_username),
    INDEX idx_access_request_created (created_at)
);

CREATE TABLE IF NOT EXISTS `micei_user_accesses` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    dmis_username VARCHAR(100) NOT NULL,
    requester_name VARCHAR(150) NOT NULL,
    dealer VARCHAR(100) NOT NULL,
    department VARCHAR(100) NOT NULL,
    module VARCHAR(100) NOT NULL,
    access_details VARCHAR(255) NULL,
    access_request_id INT NOT NULL,
    reference_no VARCHAR(40) NOT NULL,
    implemented_by VARCHAR(150) NULL,
    approved_by VARCHAR(150) NULL,
    granted_at DATETIME NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_user_access_module (dmis_username, module),
    INDEX idx_user_access_request (access_request_id)
);

CREATE TABLE IF NOT EXISTS `ntr_user_accesses` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    dmis_username VARCHAR(100) NOT NULL,
    requester_name VARCHAR(150) NOT NULL,
    dealer VARCHAR(100) NOT NULL,
    department VARCHAR(100) NOT NULL,
    module VARCHAR(100) NOT NULL,
    access_details VARCHAR(255) NULL,
    access_request_id INT NOT NULL,
    reference_no VARCHAR(40) NOT NULL,
    implemented_by VARCHAR(150) NULL,
    approved_by VARCHAR(150) NULL,
    granted_at DATETIME NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_user_access_module (dmis_username, module),
    INDEX idx_user_access_request (access_request_id)
);
